export const UserController = {
	USERSTATE_LOGIN : 'USERSTATE_LOGIN'
}

export const AboutMyJobController = {
	USER_SET_ABOUTMYJOB : 'USER_SET_ABOUTMYJOB',
	USER_GET_ABOUTMYJOBLIST : 'USER_GET_ABOUTMYJOBLIST'
}

export const CompanyList = {
	COMPANY_GET_COMPANYLIST : 'COMPANY_GET_COMPANYLIST',
	COMPANY_CLEAR_COMPANYLIST : 'COMPANY_CLEAR_COMPANYLIST'
}

export const PositionList = {
	POSITION_GET_POSITIONLIST : 'POSITION_GET_POSITIONLIST',
	POSITION_CLEAR_POSITIONLIST : 'POSITION_CLEAR_POSITIONLIST'
}

export const HotCityList = {
	HOTCITY_GET_HOTCITYLIST : 'HOTCITY_GET_HOTCITYLIST'
}

export const SearchResults = {
	COMPANY_SEARCH_COMPANYRESULTS : 'COMPANY_SEARCH_COMPANYRESULTS',
	COMPANY_SEARCHUPDATE_COMPANYRESULTS : 'COMPANY_SEARCHUPDATE_COMPANYRESULTS'
}

export const SearchPositionResults = {
	POSITION_SEARCH_POSITIONRESULTS : 'POSITION_SEARCH_POSITIONRESULTS',
	POSITION_SEARCHCLEAR_POSITIONLIST : 'POSITION_SEARCHCLEAR_POSITIONLIST'
}

export const CompanyDetail = {
	COMPANY_GET_COMPANYDETAIL : 'COMPANY_GET_COMPANYDETAIL',
	COMPANY_GET_STUDENTPOSITION : 'COMPANY_GET_STUDENTPOSITION',
	COMPANY_GET_TALK : 'COMPANY_GET_TALK',
	COMPANY_SET_FOLLOW : 'COMPANY_SET_FOLLOW'
}

export const EducationList = {
	EDUCATION_GET_EDUCATIONLIST : 'EDUCATION_GET_EDUCATIONLIST'
}

export const WorkList = {
	WORKLIST_GET_WORKLIST : 'WORKLIST_GET_WORKLIST'
}

export const CertificateList = {
	CERTIFICATELIST_GET_CERTIFICATELIST : 'CERTIFICATELIST_GET_CERTIFICATELIST'
}

export const SchoolList = {
	SCHOOLLIST_GET_SCHOOLLIST : 'SCHOOLLIST_GET_SCHOOLLIST'
}

export const ProjectList = {
	PROJECTLIST_GET_PROJECTLIST : 'PROJECTLIST_GET_PROJECTLIST'
}

export const InternshipList = {
	INTERNSHIPLIST_GET_INTERNSHIPLIST : 'INTERNSHIPLIST_GET_INTERNSHIPLIST'
}

export const DeliveryList = {
	DELIVERY_GET_DELIVERYLIST : 'DELIVERY_GET_DELIVERYLIST',
	DELIVERY_CLEAR_DELIVERYLIST : 'DELIVERY_CLEAR_DELIVERYLIST'
}